In [1]:
import numpy as np    
import pandas as pd
import os
import radiomics
import SimpleITK as sitk

In [2]:
os.chdir('C:/Users/')

In [3]:
from radiomics import featureextractor

In [4]:
extractor = featureextractor.RadiomicsFeatureExtractor(resampledPixelSpacing = [1,1,1], interpolator = 3, binWidth = 10, 
                                                      verbose = True, resegmentMode = [ 'sigma',[-3,3]])
# If we set a fixed bincount at here, there will have a warning that they recommend a fixed binWidth only

In [5]:
list_1 = ["{0:03}".format(i) for i in range(1,600)]
list_2 = ["{0:02}".format(f) for f in range(13)]

In [6]:
data_STR_clahe = pd.DataFrame()

In [18]:
for i in list_1:      
    for f in list_2:
        imgname = "STR1_VTIQ"+ str(f) + str(i) + "_hist_clahe.nrrd"
        if os.path.exists(imgname):
            img = sitk.ReadImage(imgname, sitk.sitkInt8)
            maskname = "STR1_VTIQ"+ str(f) + str(i) + "_hist_clahe_TPS.nrrd"
            if os.path.exists(maskname):
                mask = sitk.ReadImage(maskname, sitk.sitkInt8)
                try:
                    featureVector2 = extractor.execute(img, mask)
                    featureVector2["Name"]=maskname
                    df_add = pd.DataFrame([featureVector2])
                    data_STR_clahe = pd.concat([data_STR_clahe,df_add])
                except ValueError:
                    print(maskname) 
            else:
                continue

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

In [19]:
data_STR_clahe.to_excel("data_STR_clahe.xlsx")

In [12]:
STR_clahe = data_STR_clahe

In [21]:
data_STR_clahe['VTIQ Number'] = data_STR_clahe['Name'].str[9:14]

In [24]:
columns_to_move = ['VTIQ Number']
new_columns = columns_to_move + [col for col in data_STR_clahe.columns if col not in columns_to_move]
data_STR_clahe = data_B_clahe[new_columns]

In [31]:
clinical_dataset = pd.DataFrame()
clinical_dataset = pd.read_excel('updated_VTIQ_main_dataset.xlsx')

In [32]:
clinical_dataset['VTIQ Number'] = clinical_dataset['VTIQ Number'].astype(int)
data_STR_clahe['VTIQ Number'] = data_STR_clahe['VTIQ Number'].astype(int)

In [33]:
merged_df = pd.merge(clinical_dataset, data_STR_clahe, on='VTIQ Number')
merged_df

,Unnamed: 0,Unnamed: 0.1,siteno,patno,patnumber,yob,enrol,age,patno_der,bookvorh,...,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,Name
0,391,783,3,7,434,1956,1,61,7,1,...,0.02260328366690701,7.268628756743923,0.18654077030403324,140.7340036690568,7.367507847807065,0.0002840763903499835,401.9299702273926,0.12903106633977968,0.06884246952947314,B1_VTIQ03007_hist_clahe_TPS.nrrd
1,726,1453,8,6,578,1965,1,51,6,1,...,0.02475981553089177,7.208868437287886,0.21103754138297207,65.40519725661639,3.1822110098156142,0.0005277559147915587,409.4704950332806,0.10721049821481458,0.13913303374471023,B1_VTIQ08006_hist_clahe_TPS.nrrd
2,1086,2173,11,55,419,1971,1,39,55,1,...,0.03136708736125154,7.55228076447452,0.13047611804076667,472.1006126441066,2.3465186905527866,0.000860822611754073,319.518311927574,0.08710997986786548,0.18559651157333043,B1_VTIQ11055_hist_clahe_TPS.nrrd

In [34]:
columns_to_delete = ['Unnamed: 0', 'Unnamed: 0.1']
merged_df.drop(columns_to_delete, axis=1, inplace=True)

In [35]:
columns_to_move = ['VTIQ Number']
new_columns = columns_to_move + [col for col in merged_df.columns if col not in columns_to_move]
merged_df = merged_df[new_columns]

In [36]:
merged_df

,VTIQ Number,siteno,patno,patnumber,yob,enrol,age,patno_der,bookvorh,eligvorh,...,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,Name
0,3007,3,7,434,1956,1,61,7,1,1,...,0.02260328366690701,7.268628756743923,0.18654077030403324,140.7340036690568,7.367507847807065,0.0002840763903499835,401.9299702273926,0.12903106633977968,0.06884246952947314,B1_VTIQ03007_hist_clahe_TPS.nrrd
1,8006,8,6,578,1965,1,51,6,1,1,...,0.02475981553089177,7.208868437287886,0.21103754138297207,65.40519725661639,3.1822110098156142,0.0005277559147915587,409.4704950332806,0.10721049821481458,0.13913303374471023,B1_VTIQ08006_hist_clahe_TPS.nrrd
2,11055,11,55,419,1971,1,39,55,1,1,...,0.03136708736125154,7.55228076447452,0.13047611804076667,472.1006126441066,2.3465186905527866,0.000860822611754073,319.518311927574,0.08710997986786548,0.18559651157333043,B1_VTIQ11055_hist_clahe_TPS.nrrd

In [23]:
merged_df.to_excel('data_B_clahe_clinical_data.xlsx')